data<-read.csv('household_power_consumption1.csv')
data$date_time<-with(data,paste(Date,Time,sep=" "))
data$date_time<- strptime(data$date_time, format="%d/%m/%Y %H:%M:%S")
with(data,plot(data$date_time,data$Sub_metering_1,type="n"))
with(data,plot(data$date_time,data$Sub_metering_1,type="n",ylab="Energy sub metering",xlab=" "))
with(data, lines(data$date_time,data$Sub_metering_1, col="black"))
with(data, lines(data$date_time,data$Sub_metering_2, col="red"))
with(data, lines(data$date_time,data$Sub_metering_3, col="blue"))
legend("topright",legend=c("Sub_metering_1","Sun_metering_2","Submetering_3"),col=c("black","red","blue"),cex=0.6,lty="solid")
dev.copy(png,file="plot3.png")
dev.off()